### PR TITLE
[WIP] feature: Bring ReactiveUI.Fody

### PR DESCRIPTION
**Pull request by worldbeater**
ReactiveUI team has finished working on the `ReactiveUI.Fody` package so it is now <a href="https://www.nuget.org/packages/ReactiveUI.Fody/">available on NuGet</a>. `ReactiveUI.Fody` provides an efficient way of <a href="https://reactiveui.net/docs/handbook/view-models/#managing-boilerplate-code">managing boilderplate code</a>, instead of writing this:
```cs
public class ReactiveViewModel : ReactiveObject 
{
    private string password;
    public string Password
    {
        get => this.password;
        set => this.RaiseAndSetIfChanged(ref password, value);
    }
}
```
With `ReactiveUI.Fody` we would write this:
```cs
public class ReactiveViewModel : ReactiveObject 
{
    [Reactive] public string Password { get; set; }
}
```

So let's use ReactiveUI stable release and bring codegen to **Egram.Tel**! Why not? 
Let's discuss. 🥇

### CODE REVIEW

**Comment by x2bool** [comment]
Hi, thanks!

Could you please explain how this works. Does it generate code behind the scenes? If so, when this happens?

Is referencing ReactiveUI.Fody enough? Or do I have to follow some special build instructions?

**Comment by worldbeater** [comment]
@x2bool thank you for your interest!

To make `ReactiveUI.Fody` work we have to do two things:
1. `dotnet add package ReactiveUI.Fody`
2. Create a <a href="https://github.com/x2bool/egram.tel/blob/6ca4b76434112d4fbca27fe6927c282ed62940c9/Egram.Components.Authorization/FodyWeavers.xml">FodyWeavers.xml</a> file at project root to tell <a href="https://github.com/Fody/Fody">Fody</a> we'd like to use `ReactiveUI.Fody` weaver.

After we've done this, Fody will edit the IL code of our Assembly at compile time and all of our properties marked with `[Reactive]` attributes will turn into valid `ReactiveUI` properties with backing fields and `this.RaiseAndSetIfChanged` method calls.

**Comment by x2bool** [comment]
I'll merge this. However this repo is a bit outdated. I will push fresh version tomorrow. Thanks for letting me know how this works. I'll upgrade egram to use ReactiveUI.Fody everywhere.

**Comment by x2bool** [comment]
You can add this repo as an example to ReactiveUI sample apps list if you like.

**Pull request merged**
